spring:
  data:
    mongodb:
      database: local-rapid
      uri: mongodb://${MONGO_HOST:localhost:27017}/local-rapid?serverSelectionTimeoutMS=2000&connectTimeoutMS=2000
#eureka:
#  client:
#    enabled: false
eureka:
  password: ${EUREKA_USER_PASSWORD:password}
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://user:${eureka.password}@localhost:8761/eureka/
  instance:
    hostname: localhost
    nonSecurePort: 8081
java-core:
  security:
    admin-password: AckN%b51zUgOu$SE
    email-verification: false
    secure: true
    token:
      secret: NdRgUjXn2r5u8x/A?D(G+KbPeShVmYp3s6v9y$B&E)H@McQfTjWnZr4t7w!z%C*F-JaNdRgUkXp2s5v8x/A?D(G+KbPeShVmYq3t6w9z$B&E)H@McQfTjWnZr4u7x!A%
      issuer: http://job.rapid.com
      audience: e54d3a5a-2abb-11ec-8d3d-0242ac130003