name: Build and Publish Docker Image

#on:
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build with Maven
        env:
          PASSWORD: ${{ secrets.READ_PACKAGES_TOKEN }}
        run: |
          mvn -B clean package --file pom.xml --settings settings.xml
          echo "::set-output name=APP_VERSION::$(mvn --file pom.xml --settings settings.xml  -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)"
        id: build-version
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: rapid-authentication-jar
          path: target/*.jar
      - name: Save version
        uses: noobly314/share-data@v1
        with:
          share-id: app_version
          mode: set
          key: version
          value: ${{ steps.build-version.outputs.APP_VERSION }}